/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 観光地検索
         * @description テキストと画像を組み合わせて観光地を検索します。
         *     - text, imageのどちらか一方は必須
         *     - 不足している方は自動生成されます
         *     - テキスト・画像両方の類似度を計算して返却します
         *     - フロントエンド側で類似度の加算・ソートを実行します
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * @description 検索テキスト
                         * @example 美しい海岸線
                         */
                        text?: string;
                        /**
                         * Format: binary
                         * @description 検索画像
                         */
                        image?: string;
                    } | unknown | unknown;
                };
            };
            responses: {
                /** @description 検索結果 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            results: {
                                /**
                                 * @description 観光地ID
                                 * @example place_001
                                 */
                                id: string;
                                /**
                                 * @description 観光地名
                                 * @example 美ら海水族館
                                 */
                                name: string;
                                /**
                                 * @description 観光地の場所
                                 * @example 沖縄県本部町
                                 */
                                location: string;
                                /**
                                 * Format: float
                                 * @description テキスト類似度スコア (0-1の範囲)
                                 * @example 0.85
                                 */
                                text_similarity: number;
                                /**
                                 * Format: float
                                 * @description 画像類似度スコア (0-1の範囲)
                                 * @example 0.78
                                 */
                                image_similarity: number;
                            }[];
                            /** @description 検索処理のメタデータ */
                            metadata: {
                                /** @description 実際に使用された検索テキスト */
                                actual_text: string;
                                /** @description テキストが自動生成されたかどうか */
                                text_generated: boolean;
                                /** @description 画像が自動生成されたかどうか */
                                image_generated: boolean;
                                /** @description 画像が存在するかどうか */
                                has_image: boolean;
                                /** @description 元の入力テキスト */
                                original_text?: string | null;
                                /** @description 元の画像が存在するかどうか */
                                has_original_image: boolean;
                            };
                        };
                    };
                };
                /** @description パラメータエラー */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPException"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suggest-images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 画像提案
         * @description システム保有画像からランダムに6枚を提案
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 提案画像リスト */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example [
                             *       "images (1).jpg",
                             *       "IMG_20241221_200910.jpg",
                             *       "IMG_7712.jpeg",
                             *       "函館のきれいな海.jpg",
                             *       "函館のとてもきれいな景色.jpg",
                             *       "55FF9164-B5D7-4000-94F0-D78047B68EB2.jpeg"
                             *     ] */
                            suggested_images: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HTTPException: {
            /**
             * @description エラーメッセージ
             * @example text または image のいずれかは必須です
             */
            detail: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
